
version: '3.7'

services:
  psql:
    image: postgres@sha256:832e01fa055c55a9c9195db231cf3935a81b7b60c8cccd64e7b5395d1ee1948b
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  archiver-psql:
    image: docker-registry.siecobywatelska.plremote-archiver
    build:
      context: .
    environment:
      BACKUP_SRC: "postgresql"
      BACKUP_POSTGRESQL_HOST: db
      BACKUP_POSTGRESQL_HOST: psql
      BACKUP_POSTGRESQL_DATABASE: db
      BACKUP_POSTGRESQL_USER: root
      BACKUP_POSTGRESQL_PASSWORD: pass
    depends_on:
      - psql

  mysql:
    image: mysql@sha256:77b7e09c906615c1bb59b2e9d7703f728b1186a5a70e547ce2f1079ef4c1c5ca
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass

  archiver-mysql:
    build:
      context: .
    environment:
      BACKUP_SRC: "mysql"
      BACKUP_MYSQL_HOST: mysql
      BACKUP_MYSQL_DATABASE: db
      BACKUP_MYSQL_USER: root
      BACKUP_MYSQL_PASSWORD: example
    depends_on:
      - mysql
