
version: '3.7'

services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  archiver-psql:
    build:
      context: .
    environment:
      BACKUP_SRC: "postgresql"
      BACKUP_POSTGRESQL_HOST: psql
      BACKUP_POSTGRESQL_DATABASE: db
      BACKUP_POSTGRESQL_USER: root
      BACKUP_POSTGRESQL_PASSWORD: pass
    depends_on:
      - psql

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass

  archiver-mysql:
    build:
      context: .
    environment:
      BACKUP_SRC: "mysql"
      BACKUP_MYSQL_HOST: mysql
      BACKUP_MYSQL_DATABASE: db
      BACKUP_MYSQL_USER: root
      BACKUP_MYSQL_PASSWORD: example
    depends_on:
      - mysql
