name: Docker Image CI

on:
  push:

jobs:
  build:
    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        image:
        - "alpine-curl"
        - "azure-export"
        - "civicrm-php"
        - "civicrm-sshd"
        - "debian-shell"
        - "metabase-watchdog"
        - "mixpanel-proxy"
        - "mycli"
        - "nodejs-ftp-srv"
        - "pyupgrade"
        - "remote-archiver"
        - "rsyslogd"
        - "schedule-bot"
        - "terraform-tfnotify"
        - "travis-cli"
        - "ubuntu-sshd-github"
        - "yq"
        - "zabbix-agent"
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_URL: quay.io
      DOCKER_IMAGE: quay.io/watchdogpolska/${{ matrix.image }}:latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull image (best effort)
      run: docker pull ${DOCKER_IMAGE} || echo 'Failed to pull'
    - name: Build image
      run: docker build --cache-from "${DOCKER_IMAGE}" --tag "${DOCKER_IMAGE}" ${{ matrix.image }}
    - name: "Docker login"
      env:
        # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.QUAY_DOCKER_USERNAME }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY_URL}
      if: "github.ref == 'refs/heads/master'"
    - name: Push image
      run: docker push 
      if: "github.ref == 'refs/heads/master'"
