name: Docker Image CI

on:
  push:

jobs:
  build:
    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        image:
        - "alpine-curl"
        - "azure-export"
        - "civicrm-php"
        - "civicrm-sshd"
        - "debian-shell"
        - "metabase-watchdog"
        - "mixpanel-proxy"
        - "mycli"
        - "nodejs-ftp-srv"
        - "pyupgrade"
        - "remote-archiver"
        - "rsyslogd"
        - "schedule-bot"
        - "terraform-tfnotify"
        - "travis-cli"
        - "ubuntu-sshd-github"
        - "yq"
        - "zabbix-agent"
        - "apache-tika"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.QUAY_DOCKER_USERNAME }}
        password: ${{ secrets.QUAY_DOCKER_PASSWORD }}
        repository: "watchdogpolska/${{ matrix.image }}"
        registry: 'quay.io'
        path: '${{ matrix.image }}'
        tag_with_ref: true
        add_git_labels: true